version: '3'

services:
  backend:
    build: ./dashboard_back
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - DEBUG=1
  frontend:
    build: ./dashboard_front
    ports:
      - "8081:8081"
    expose:
      - 8081
    depends_on:
      - backend